### ISSUE TITLE
migrate drupal 8 site from one platform to another

### ISSUE THREAD

**Issue by Lowell20** [omega8cc/boa#1077]
I have a new boa install that I can't migrate a vanilla drupal 8.2.0 site from one identical platform to another. 
Here is the error message I am getting

```
Drush command terminated abnormally due to an unrecoverable error.  
Error: Uncaught Error: Class 'Symfony\Component\HttpFoundation\Request' not found in /data/disk/o1/tools/drush/lib/Drush/Boot/DrupalBoot8.php:61  
Stack trace:  
#0 /data/disk/o1/tools/drush/lib/Drush/Boot/DrupalBoot.php(391): Drush\Boot\DrupalBoot8->conf_path(true, true)  
#1 /data/disk/o1/tools/drush/lib/Drush/Boot/DrupalBoot.php(333): Drush\Boot\DrupalBoot->bootstrap_drupal_site_validate_settings_present()  
#2 /data/disk/o1/tools/drush/includes/bootstrap.inc(430): Drush\Boot\DrupalBoot->bootstrap_drupal_site_validate()  
#3 /data/disk/o1/tools/drush/includes/bootstrap.inc(351): drush_bootstrap_validate(2)  
#4 /data/disk/o1/.drush/sys/provision/platform/deploy.provision.inc(92): drush_bootstrap(2)  
#5 /data/disk/o1/tools/drush/includes/command.inc(373): drush_provision_drupal_pre_provision_deploy('/data/disk/o1/b...')  
#6 /data/disk/o1/tools/drush/includes/command.inc(224): _drush_invoke_hooks(Array, Array)  
#7 /data/disk/o1/tools/drush/includes/command.inc(192): drush_command('/data/disk/o1/b...')  
#8 /data/disk/o1/tools/drush in /data/disk/o1/tools/drush/lib/Drush/Boot/DrupalBoot8.php, line 61
```

Looking for ideas or suggestions

**Comment by omega8cc** [comment]
Please always follow [guidelines](https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt).

**Comment by petrovich69** [comment]
Вы ничего не ответили про почту.
