### ISSUE TITLE
Twig Debbuging in Drupal 8.2.x and BOA

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#1085]
I am trying to make the first steps for D8 with BOA.

I found this: https://github.com/omega8cc/boa/blob/8e866b43e2862b6a8fd965d4260184e9ef1d38fc/aegir/conf/global.inc#L337
which says that development.services.yml should be under the files directory (line 321 in the same file).

So, in my site I add this file `files/development.services.yml`:

```
parameters:
  twig.config:
    debug: true
    auto_reload: true
    cache: false
```

But it doesn't seem to have much effect. 
I did a `drush cr` as I had to.
When accessing the site from a dev alias I get this in a whitescreen:
`The website encountered an unexpected error. Please try again later.`
When accessing the site from its normal domain there is no debug information, as expected.

I then edited local.settings.php and added those two lines:

```
        $settings['cache']['bins']['render'] = 'cache.backend.null';
        $settings['cache']['bins']['dynamic_page_cache'] = 'cache.backend.null';
```

From here on, a `drush cr` and Aegir flush cache fail with:

```
exception 'Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException' with message 'You have requested a non-existent service "cache.backend.null". Did you mean one of these: "cache.backend.memory", "cache.backend.apcu", "cache.backend.php"?' in /data/disk/srm/static/drupal-8.2.x/core/lib/Drupal/Component/DependencyInjection/Container.php:157
Stack trace:
#0 /data/disk/srm/static/drupal-8.2.x/core/lib/Drupal/Core/Cache/CacheFactory.php(83): Drupal\Component\DependencyInjection\Container->get('cache.backend.n...')
#1 [internal function]: Drupal\Core\Cache\CacheFactory->get('render')
#2 /data/disk/srm/static/drupal-8.2.x/core/lib/Drupal/Component/DependencyInjection/Container.php(254): call_user_func_array(Array, Array)
#3 /data/disk/srm/static/drupal-8.2.x/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\Container->createService(Array, 'cache.render')
#4 /data/disk/srm/static/drupal-8.2.x/core/lib/Drupal/Core/Cache/Cache.php(158): Drupal\Component\DependencyInjection\Container->get('cache.render')
#5 /data/disk/srm/static/drupal-8.2.x/core/includes/utility.inc(44): Drupal\Core\Cache\Cache::getBins()
#6 /data/disk/srm/tools/drush/commands/core/cache.drush.inc(291): drupal_rebuild(Object(Composer\Autoload\ClassLoader), Object(Symfony\Component\HttpFoundation\Request))
#7 [internal function]: drush_cache_rebuild()
#8 /data/disk/srm/tools/drush/includes/command.inc(373): call_user_func_array('drush_cache_reb...', Array)
#9 /data/disk/srm/tools/drush/includes/command.inc(224): _drush_invoke_hooks(Array, Array)
#10 [internal function]: drush_command()
#11 /data/disk/srm/tools/drush/includes/command.inc(192): call_user_func_array('drush_command', Array)
#12 /data/disk/srm/tools/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#13 /data/disk/srm/tools/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#14 /data/disk/srm/tools/drush/drush.php(12): drush_main()
#15 {main}
```

I do not know what I missed. Am I interpreting the directory structure wrong?

**Comment by bserem** [comment]
It turns out that the contents of the `development.services.yml` files must be:

```
services:
  cache.backend.null:
    class: Drupal\Core\Cache\NullBackendFactory

parameters:
  twig.config:
    debug: true 
    auto_reload: true
    cache: false
```

Note the first lines!
I did no changes on local.settings.php.
Works nice (and fast) without the need to `drush cr` after every change.

**Comment by omega8cc** [comment]
We need to document this better.

**Comment by bserem** [comment]
I did an attempt. Tell me if you like this approach.

**Comment by omega8cc** [comment]
Thanks for the commit and sorry for the wait time, we totally forgot about it, it seems :|
