### ISSUE TITLE
Backboa restore: "Cannot allocate memory"

### ISSUE THREAD

**Issue by dnotes** [omega8cc/boa#1269]
Trying to restore a file using backboa, I'm getting out of memory errors:

```
2589 (process ID) old priority 10, new priority 19
Traceback (most recent call last):
  File "/usr/local/bin/duplicity", line 1546, in <module>
    with_tempdir(main)
  File "/usr/local/bin/duplicity", line 1540, in with_tempdir
    fn()
  File "/usr/local/bin/duplicity", line 1391, in main
    do_backup(action)
  File "/usr/local/bin/duplicity", line 1468, in do_backup
    restore(col_stats)
  File "/usr/local/bin/duplicity", line 731, in restore
    restore_get_patched_rop_iter(col_stats)):
  File "/usr/local/lib/python2.7/dist-packages/duplicity/patchdir.py", line 560, in Write_ROPaths
    for ropath in rop_iter:
  File "/usr/local/lib/python2.7/dist-packages/duplicity/patchdir.py", line 523, in integrate_patch_iters
    for patch_seq in collated:
  File "/usr/local/lib/python2.7/dist-packages/duplicity/patchdir.py", line 389, in yield_tuples
    setrorps(overflow, elems)
  File "/usr/local/lib/python2.7/dist-packages/duplicity/patchdir.py", line 378, in setrorps
    elems[i] = iter_list[i].next()
  File "/usr/local/lib/python2.7/dist-packages/duplicity/patchdir.py", line 107, in filter_path_iter
    for path in path_iter:
  File "/usr/local/lib/python2.7/dist-packages/duplicity/patchdir.py", line 121, in difftar2path_iter
    tarinfo_list = [tar_iter.next()]
  File "/usr/local/lib/python2.7/dist-packages/duplicity/patchdir.py", line 339, in next
    self.set_tarfile()
  File "/usr/local/lib/python2.7/dist-packages/duplicity/patchdir.py", line 333, in set_tarfile
    self.current_fp = self.fileobj_iter.next()
  File "/usr/local/bin/duplicity", line 768, in get_fileobj_iter
    manifest.volume_info_dict[vol_num])
  File "/usr/local/bin/duplicity", line 811, in restore_get_enc_fileobj
    fileobj = tdp.filtered_open_with_delete("rb")
  File "/usr/local/lib/python2.7/dist-packages/duplicity/dup_temp.py", line 119, in filtered_open_with_delete
    fh = FileobjHooked(path.DupPath.filtered_open(self, mode))
  File "/usr/local/lib/python2.7/dist-packages/duplicity/path.py", line 778, in filtered_open
    return gpg.GPGFile(False, self, gpg_profile)
  File "/usr/local/lib/python2.7/dist-packages/duplicity/gpg.py", line 202, in __init__
    'logger': self.logger_fp})
  File "/usr/local/lib/python2.7/dist-packages/duplicity/gpginterface.py", line 374, in run
    create_fhs, attach_fhs)
  File "/usr/local/lib/python2.7/dist-packages/duplicity/gpginterface.py", line 414, in _attach_fork_exec
    process.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

I found [this issue](https://bugs.launchpad.net/duplicity/+bug/1720159) and it looks like it may have been fixed in a newer version, but `backboa install` just tries to install 0.7.11. What would you recommend?

**Comment by omega8cc** [comment]
Not sure if this is Duplicity issue or your server needs more RAM perhaps? We have never experienced this problem even with huge backups.

**Comment by omega8cc** [comment]
Please create an empty control file `/root/.backboa.autoupdate`, wait 10 minutes, then re-login as root and run `backboa install`. Let us know if this helped.
