### ISSUE TITLE
Migrated sites failing because they -don't- have CiviCRM

### ISSUE THREAD

**Issue by aDarkling** [omega8cc/boa#1274]
New BOA installation on virgin server
Plain Drupal 7.58 platform migrated from (non-BOA) Aegir 7.3.x installation on old server via "copy & verify"
Platform contained 9 sites.  1 has CiviCrm installed.  The others do not.
All of the non-CiviCRM sites are failing verification with the following error:

`exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bygeorgetechcom.civicrm_domain' doesn't exist' in /data/disk/o1/static/drupal-7/includes/database/database.inc:2227
Stack trace:
#0 /data/disk/o1/static/drupal-7/includes/database/database.inc(2227): PDOStatement->execute(Array)
#1 /data/disk/o1/static/drupal-7/includes/database/database.inc(697): DatabaseStatementBase->execute(Array, Array)
#2 /data/disk/o1/static/drupal-7/includes/database/database.inc(2406): DatabaseConnection->query('select version ...', Array, Array)
#3 /data/disk/o1/aegir/distro/001/profiles/hostmaster/modules/aegir/hosting_civicrm/drush/provision_civicrm.inc(773): db_query('select version ...', Array)
#4 /data/disk/o1/aegir/distro/001/profiles/hostmaster/modules/aegir/hosting_civicrm/drush/provision_civicrm.inc(726): _provision_civicrm_database_version()
#5 /data/disk/o1/aegir/distro/001/profiles/hostmaster/modules/aegir/hosting_civicrm/drush/verify.provision.inc(47): _provision_civicrm_check_upgrade_mode()
#6 [internal function]: drush_provision_civicrm_provision_verify()
#7 /data/disk/o1/tools/drush/includes/command.inc(422): call_user_func_array('drush_provision...', Array)
#8 /data/disk/o1/tools/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#9 [internal function]: drush_command()
#10 /data/disk/o1/tools/drush/includes/command.inc(199): call_user_func_array('drush_command', Array)
#11 /data/disk/o1/tools/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#12 /data/disk/o1/tools/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#13 /data/disk/o1/tools/drush/drush.php(12): drush_main()
#14 {main}`

They all seem to be getting civicrm.settings.php created in their directories for some odd reason.
Anyone know what this is about?

**Comment by ar-jan** [comment]
I think a platform with CiviCRM always gets CiviCRM installed/expected by BOA, so you'd have to separate it into separate platforms with and without Civi. (If I remember correctly, it's been a while; I'm just a (previous) user of Civi on BOA).

**Comment by aDarkling** [comment]
Yes, I think you're right about that.  I got the sites to verify by uninstalling the Aegir civicrm modules and deleting the civicrm.settings.php files that it'd placed in every site directory.

BTW, "(previous) user of Civi" -- is there a story behind that?

**Comment by ar-jan** [comment]
Not really, it was at a previous job. I think CiviCRM wins on features and reasonable defaults, but it's also a huge beast, just like Drupal, so depending on the use case perhaps something simpler would be more maintainable.
