### ISSUE TITLE
Backboa failing to backup

### ISSUE THREAD

**Issue by dnotes** [omega8cc/boa#1291]
[boa info more](https://gist.github.com/dnotes/1e761f347c1c40c430c9b82c7f19f886)

`backboa backup` fails on all my servers, with the following error:

```
host:~# backboa backup
2420 (process ID) old priority 10, new priority 19
The duplicity backup is starting now...
Traceback (most recent call last):
  File "/usr/local/bin/duplicity", line 1546, in <module>
    with_tempdir(main)
  File "/usr/local/bin/duplicity", line 1540, in with_tempdir
    fn()
  File "/usr/local/bin/duplicity", line 1391, in main
    do_backup(action)
  File "/usr/local/bin/duplicity", line 1510, in do_backup
    full_backup(col_stats)
  File "/usr/local/bin/duplicity", line 575, in full_backup
    globals.backend)
  File "/usr/local/bin/duplicity", line 432, in write_multivol
    globals.volsize)
  File "/usr/local/lib/python2.7/dist-packages/duplicity/gpg.py", line 352, in GPGWriteFile
    file = GPGFile(True, path.Path(filename), profile)
  File "/usr/local/lib/python2.7/dist-packages/duplicity/gpg.py", line 183, in __init__
    'logger': self.logger_fp})
  File "/usr/local/lib/python2.7/dist-packages/duplicity/gpginterface.py", line 374, in run
    create_fhs, attach_fhs)
  File "/usr/local/lib/python2.7/dist-packages/duplicity/gpginterface.py", line 414, in _attach_fork_exec
    process.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

The duplicity backup is complete!
```

Status and test commands complete without errors. Here is the output from status command: 

```
# backboa status
28100 (process ID) old priority 10, new priority 19
Collection Status
-----------------
Connecting with backend: BackendWrapper
Archive dir: /root/.cache/duplicity/[...]

Found 0 secondary backup chains.

Found primary backup chain with matching signature chain:
-------------------------
Chain start time: Mon Mar 19 00:16:17 2018
Chain end time: Mon Mar 19 00:16:17 2018
Number of contained backup sets: 1
Total number of contained volumes: 52
 Type of backup set:                            Time:      Num volumes:
                Full         Mon Mar 19 00:16:17 2018                52
-------------------------
No orphaned or incomplete backup sets found.
```

Here is sample info from .barracuda.cnf file, minus sensitive data:
```
_AWS_KEY=[redacted]
_AWS_SEC=[redacted]
_AWS_PWD=[redacted]
_AWS_REG='us-west-2'
_AWS_TTL='30D'
_AWS_FLC='7D'
_AWS_VLV='1'
_AWS_PRG='NO'
```

I do get email updates on a regular basis. The incremental update emails are blank, with only the two lines, but the full backup emails display the output of `backboa status`, which is confusing because there is a full backup, so at a glance it looks like it was successful. I have also tried `backboa install` but it says `Latest duplicity version 0.7.11 already installed`—even though this is not the most recent version.

**Comment by omega8cc** [comment]
Please upgrade barracuda to head and not stable and see if that helps. We don't use the outdated stable for months, so we may not be aware of such issues, which we don't experience with barracuda head (which is actually the new 'stable').
