### ISSUE TITLE
Backboa 0.7.18.2 misses monotonic on Ubuntu precise

### ISSUE THREAD

**Issue by timlie** [omega8cc/boa#1321]
Hi,

These are my boa info files:

https://gist.github.com/timlie/ae548ace4ff3500e9baed24639b3ff64
https://gist.github.com/timlie/252512b087ef239b949cd0ed73d4efde

When using backboa I get the following errors (backboa status command):

`27927 (process ID) old priority 0, new priority 19
Traceback (most recent call last):
  File "/usr/local/bin/duplicity", line 42, in <module>
    import fasteners
  File "/usr/local/lib/python2.7/dist-packages/fasteners-0.14.1-py2.7.egg/fasteners/__init__.py", line 23, in <module>
    from fasteners.lock import locked  # noqa
  File "/usr/local/lib/python2.7/dist-packages/fasteners-0.14.1-py2.7.egg/fasteners/lock.py", line 24, in <module>
    from fasteners import _utils
  File "/usr/local/lib/python2.7/dist-packages/fasteners-0.14.1-py2.7.egg/fasteners/_utils.py", line 22, in <module>
    from monotonic import monotonic as now  # noqa
ImportError: No module named monotonic`

If I remove duplicity from /usr/local/bin and change the value of _DUPLICITY_VRN in /opt/local/bin/backboa to 0.7.12 (which i saw referenced here) the backboa script works, only it gets overwritten every day by daily.sh

How can we fix this? Thanks!

**Comment by omega8cc** [comment]
Thank you for the report. We didn’t test this with Ubuntu honestly, but we should try to make it work anyway.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
