### ISSUE TITLE
Sites don't work until cache clear or redis server restart

### ISSUE THREAD

**Issue by kaszarobert** [omega8cc/boa#1541]
Recently, Drupal 8 sites seem to malfunction after a certain period of time. They're running OK for a few days but then suddenly some of them starting to produce WSOD for every user and these kind of messages starting to appear in error logs:

 ```
 Sep 25 03:33:29 hostmaster drupal: http://www.mysite.sk|1600997609|php|127.0.0.1|http://www.mysite.sk/||0||Drupal\Core\Entity\Exception\NoCorrespondingEntityClassException: The Drupal\user\Entity\User class does not correspond to an entity type. in Drupal\Core\Entity\EntityTypeRepository->getEntityTypeFromClass() (line 98 of /data/disk/o1/static/mysite/core/lib/Drupal/Core/Entity/EntityTypeRepository.php) #0 /data/disk/o1/static/mysite/core/lib/Drupal/Core/Entity/EntityBase.php(531): Drupal\Core\Entity\EntityTypeRepository->getEntityTypeFromClass('Drupal\\user\\Ent...')#012#1 /opt/tools/drush/8/drush/lib/Drush/User/User8.php(26): Drupal\Core\Entity\EntityBase::load(0)#012#2 /opt/tools/drush/8/drush/lib/Drush/Boot/DrupalBoot.php(558): Drush\User\User8->load_by_uid(0)#012#3 /opt/tools/drush/8/drush/includes/bootstrap.inc(354): Drush\Boot\DrupalBoot->bootstrap_drupal_login()#012#4 /opt/tools/drush/8/drush/includes/bootstrap.inc(473): drush_bootstrap(6, 6)#012#5 /opt/tools/drush/8/drush/lib/Drush/Boot/BaseBoot.php(59): drush_bootstrap_to_phase(6)#012#6 /opt/tools/drush/8/drush/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()#012#7 /opt/tools/drush/8/drush/drush.php(12): drush_main()#012#8 {main}.

InvalidArgumentException: "Class "\Drupal\system\Controller\Http4xxController" does not exist." at /data/disk/o1/static/mysite-8.6.10/core/lib/Drupal/Core/DependencyInjection/ClassResolver.php line 24

InvalidArgumentException: "No check has been registered for access_check.permission" at /data/disk/o1/static/mysite-8.6.2/core/lib/Drupal/Core/Access/CheckProvider.php line 97

Exception Drupal\Component\Plugin\Exception\PluginNotFoundException: "The "node" entity type does not exist." at /data/disk/o1/static/mysite-8.6.2/core/lib/Drupal/Core/Entity/EntityTypeManager.php line 133

Exception Drupal\Component\Plugin\Exception\PluginNotFoundException: "The "user_role" entity type does not exist." at /data/disk/o1/static/mysite/core/lib/Drupal/Core/Entity/EntityTypeManager.php line 150

Error: Call to undefined method Drupal\Core\EventSubscriber\RedirectResponseSubscriber::sanitizeDestination() in /data/disk/o1/static/mysite/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php on line 111 #0 /data/disk/o1/static/mysite/vendor/symfony/http-kernel/HttpKernel.php(125): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
 ```

The sites start working immediately after I run drush cr for each of them manually or if I restart the redis server. All the error messages indicate that Drupal cannot find the needed PHP files and classes for some reason and the page rendering fails.

`boa info` output:
https://gist.github.com/kaszarobert/ad03fc351ebc1f002da37da3ba23e630

**Comment by Juc1** [comment]
@kaszarobert did you get anywhere with this? I am having the same problem with "The "node" entity type does not exist" and "The "user_role" entity type does not exist."

**Comment by omega8cc** [comment]
You are running seriously outdated and no longer supported BOA version. Please upgrade both barracuda and octopus to head.
