### ISSUE TITLE
barracuda up-head drush error - Call to undefined function provision_autoload_register_prefix

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#1569]
Hi all

I am using Digital Ocean. 

$ barracuda up-head fails with Drush error below

Full upgrade log and $ boa info here https://pastebin.com/tuCWmBmq

Any ideas please?

```
BOA [18:56:58] ==> INFO: Test OK, we can proceed with Hostmaster upgrade
BOA [18:56:58] ==> INFO: Moving old directories
BOA [18:56:58] ==> INFO: Downloading drush 8.4.9-dev...
BOA [18:57:04] ==> INFO: Installing Aegir Provision backend...
BOA [18:57:04] ==> INFO: Downloading Drush and Provision extensions...
Drush command terminated abnormally due to an unrecoverable error.                                                                              [error]
Error: Uncaught Error: Call to undefined function provision_autoload_register_prefix() in
/var/aegir/hostmaster-BOA-4.1.3/profiles/hostmaster/modules/aegir/aegir_objects/drush/aegir_objects.drush.inc:15
Stack trace:
#0 /var/aegir/hostmaster-BOA-4.1.3/profiles/hostmaster/modules/aegir/aegir_objects/drush/aegir_objects.drush.inc(23):
aegir_objects_register_autoload()
#1 /var/aegir/drush/includes/command.inc(226): aegir_objects_drush_init()
#2 /var/aegir/drush/includes/command.inc(199): drush_command()
#3 /var/aegir/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#4 /var/aegir/drush/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#5 /var/aegir/drush/drush.php(12): drush_main()
#6 {main}
  thrown in /var/aegir/hostmaster-BOA-4.1.3/profiles/hostmaster/modules/aegir/aegir_objects/drush/aegir_objects.drush.inc, line 15
BOA [18:57:11] ==> FATAL ERROR: Drush is broken (/opt/php73/bin/php /var/aegir/drush/drush.php help failed)
BOA [18:57:11] ==> FATAL ERROR: Aborting AegirUpgrade installer NOW!
BOA [18:57:11] ==> FATAL ERROR: AegirUpgrade installer failed
BOA [18:57:11] ==> FATAL ERROR: Aborting Barracuda installer NOW!
```

**Comment by omega8cc** [comment]
This could be a temporary network error related, which prevented the procedure from downloading all components.

Just try again.

Also, you should remove `--with-freetype-dir=/usr` from `_PHP_EXTRA` as it should be managed automatically depending on the PHP versions installed.

**Comment by Juc1** [comment]
@omega8cc ok thanks but...

> Also, you should remove --with-freetype-dir=/usr from _PHP_EXTRA

how / where do I do that?

**Comment by omega8cc** [comment]
The `_PHP_EXTRA_CONF` is `/root/.barracuda.cnf` variable. It should be empty.
