### ISSUE TITLE
Upgrade from Beowulf to Chimaera fails

### ISSUE THREAD

**Issue by fotiDim** [omega8cc/boa#1770]
I am running BOA 4  on Stretch. I tried to do the automatic upgrade method.

`barracuda up-head system` and
`reboot`
work fine. I upgraded to BOA 5.1.0 successfully and websites work fine.

If I proceed with
`touch /root/.run-to-chimaera.cnf`
`service clean-boa-env start` and wait overnight, I end up with Beowulf and non functioning websites. It seems that Redis fails to start. Not even the Aegir dashboard works.

I am getting an `ALERT: Failed (apt) Barracuda upgrade on my.server.com at 231225-015451` email:

```
BOA [01:55:20] ==> Skynet Agent v.BOA-5.1.0-head welcomes you aboard!

BOA [01:55:23] ==> MODE: UPGRADE

BOA [01:55:50] ==> VIRT: This system is supported: Linux KVM guest

BOA [01:55:51] ==> Aegir on [my.server.com](http://my.server.com/) Devuan/beowulf x86_64 PHP 7.4

BOA [01:56:22] ==> INFO: Running aptitude full-upgrade...
apt --fix-broken install -y failed.  Error (if any): 0

Displaying the last 15 lines of logfile
  /var/backups/barracuda-upgrade-231225-015506.log
to help troubleshoot this problem

If you see any error with advice to run 'dpkg --configure --force-all -a'
run this command with default answer, then run this installer again

        at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:92)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.jca.ProviderList.fromSecurityProperties(ProviderList.java:91)
        at java.base/sun.security.jca.Providers.<clinit>(Providers.java:54)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:156)
        at java.base/java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:193)
        at org.debian.security.KeyStoreHandler.<init>(KeyStoreHandler.java:50)
        at org.debian.security.UpdateCertificates.<init>(UpdateCertificates.java:65)
        at org.debian.security.UpdateCertificates.main(UpdateCertificates.java:51)
E: /etc/ca-certificates/update.d/jks-keystore exited with code 1.
done.
Errors were encountered while processing:
 grub-pc
 ca-certificates-java
 openjdk-11-jre-headless:amd64
dpkg --configure --force-all -a failed.  Error (if any): 0

Displaying the last 15 lines of logfile
  /var/backups/barracuda-upgrade-231225-015506.log
to help troubleshoot this problem

If you see any error with advice to run 'dpkg --configure --force-all -a'
run this command with default answer, then run this installer again

update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
Processing triggers for ca-certificates (20200601~deb10u2) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
done.
BOA [01:57:17] ==> INFO: Cleaning up any systemd remnants...
BOA [01:58:21] ==> INFO: Removing any packages orphaned by the migration process...
BOA [01:58:28] ==> INFO: Running dist-upgrade to complete the system upgrade...
BOA [01:58:28] ==> WAIT: This may take a while, please wait...
BOA [01:58:40] ==> INFO: The post_major_os_upgrade procedure is complete
BOA [01:58:57] ==> INFO: Running system packages update...
BOA [02:00:14] ==> INFO: Upgrading required libraries and tools...
BOA [02:01:04] ==> INFO: Running aptitude full-upgrade...
apt --fix-broken install -y failed.  Error (if any): 0

Displaying the last 15 lines of logfile
  /var/backups/barracuda-upgrade-231225-015506.log
to help troubleshoot this problem

If you see any error with advice to run 'dpkg --configure --force-all -a'
run this command with default answer, then run this installer again

Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up grub-pc (2.06-3~deb10u4) ...
/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-0 does not exist, so cannot grub-install to it!
You must correct your GRUB install devices before proceeding:

  DEBIAN_FRONTEND=dialog dpkg --configure grub-pc
  dpkg --configure -a
dpkg: error processing package grub-pc (--configure):
 installed grub-pc package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 grub-pc
dpkg --configure --force-all -a failed.  Error (if any): 0

Displaying the last 15 lines of logfile
  /var/backups/barracuda-upgrade-231225-015506.log
to help troubleshoot this problem

If you see any error with advice to run 'dpkg --configure --force-all -a'
run this command with default answer, then run this installer again

Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up grub-pc (2.06-3~deb10u4) ...
/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-0 does not exist, so cannot grub-install to it!
You must correct your GRUB install devices before proceeding:

  DEBIAN_FRONTEND=dialog dpkg --configure grub-pc
  dpkg --configure -a
dpkg: error processing package grub-pc (--configure):
 installed grub-pc package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 grub-pc
Setting up grub-pc (2.06-3~deb10u4) ...
BOA [02:01:30] ==> INFO: Upgrading a large list of libraries and tools...
BOA [02:01:30] ==> WAIT: This may take a while, please wait...
/usr/bin/aptitude -f -y -q       --allow-untrusted       -o Dpkg::Options::=--force-confdef       -o Dpkg::Options::=--force-confold install postfix postfix-pcre failed.  Error (if any): 0

Displaying the last 15 lines of logfile
  /var/backups/barracuda-upgrade-231225-015506.log
to help troubleshoot this problem

If you see any error with advice to run 'dpkg --configure --force-all -a'
run this command with default answer, then run this installer again


  DEBIAN_FRONTEND=dialog dpkg --configure grub-pc
  dpkg --configure -a
dpkg: error processing package grub-pc (--configure):
 installed grub-pc package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 grub-pc
Setting up grub-pc (2.06-3~deb10u4) ...
Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...
Initializing package states...
Writing extended state information...
Building tag database...
/usr/bin/aptitude -f -y -q       --allow-untrusted       -o Dpkg::Options::=--force-confdef       -o Dpkg::Options::=--force-confold install  failed.  Error (if any): 0

Displaying the last 15 lines of logfile
  /var/backups/barracuda-upgrade-231225-015506.log
to help troubleshoot this problem

If you see any error with advice to run 'dpkg --configure --force-all -a'
run this command with default answer, then run this installer again

dpkg: error processing package grub-pc (--configure):
 installed grub-pc package post-installation script subprocess returned error exit status 1
Setting up gnupg-agent (2.2.12-1+deb10u2) ...
Setting up libgvc6-plugins-gtk (2.40.1-6+deb10u1) ...
Processing triggers for libc-bin (2.28-10+deb10u2) ...
Errors were encountered while processing:
 grub-pc
Setting up grub-pc (2.06-3~deb10u4) ...
Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...
Initializing package states...
Writing extended state information...
Building tag database...
/usr/bin/aptitude -f -y -q       --allow-untrusted       -o Dpkg::Options::=--force-confdef       -o Dpkg::Options::=--force-confold install libmcrypt-dev failed.  Error (if any): 0

Displaying the last 15 lines of logfile
  /var/backups/barracuda-upgrade-231225-015506.log
to help troubleshoot this problem

If you see any error with advice to run 'dpkg --configure --force-all -a'
run this command with default answer, then run this installer again


  DEBIAN_FRONTEND=dialog dpkg --configure grub-pc
  dpkg --configure -a
dpkg: error processing package grub-pc (--configure):
 installed grub-pc package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 grub-pc
Setting up grub-pc (2.06-3~deb10u4) ...
Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...
Initializing package states...
Writing extended state information...
Building tag database...
/usr/bin/aptitude -f -y -q       --allow-untrusted       -o Dpkg::Options::=--force-confdef       -o Dpkg::Options::=--force-confold install imagemagick libmagickwand-dev graphviz libgraphviz-dev                      libgd3                      libkrb5-dev                      libldap-dev                      libxpm-dev                      libwebp-dev                      autoconf2.64                      automake1.11                      automake-1.15                      automake-1.16                      gnupg1-curl                      libpcre2-dev                      libpcre2-posix0                      libpcre3                      libpcre3-dev                      libpng-dev                      libpng16-16                      libtinfo6                      software-properties-common                      ttf-dejavu                      ttf-dejavu-core                      ttf-dejavu-extra                      screen failed.  Error (if any): 0

Displaying the last 15 lines of logfile
  /var/backups/barracuda-upgrade-231225-015506.log
to help troubleshoot this problem

If you see any error with advice to run 'dpkg --configure --force-all -a'
run this command with default answer, then run this installer again

  DEBIAN_FRONTEND=dialog dpkg --configure grub-pc
  dpkg --configure -a
dpkg: error processing package grub-pc (--configure):
 installed grub-pc package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 grub-pc
Setting up grub-pc (2.06-3~deb10u4) ...
Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...
Initializing package states...
Writing extended state information...
Building tag database...
/usr/bin/aptitude -f -y -q       --allow-untrusted       -o Dpkg::Options::=--force-confdef       -o Dpkg::Options::=--force-confold install rsyslog failed.  Error (if any): 0

Displaying the last 15 lines of logfile
  /var/backups/barracuda-upgrade-231225-015506.log
to help troubleshoot this problem

If you see any error with advice to run 'dpkg --configure --force-all -a'
run this command with default answer, then run this installer again


  DEBIAN_FRONTEND=dialog dpkg --configure grub-pc
  dpkg --configure -a
dpkg: error processing package grub-pc (--configure):
 installed grub-pc package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 grub-pc
Setting up grub-pc (2.06-3~deb10u4) ...
Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...
Initializing package states...
Writing extended state information...
Building tag database...
apt-get install tree -fuy --allow-unauthenticated -q --config-file /opt/tmp/apt.conf.noi.nrml failed.  Error (if any): 0

Displaying the last 15 lines of logfile
  /var/backups/barracuda-upgrade-231225-015506.log
to help troubleshoot this problem

If you see any error with advice to run 'dpkg --configure --force-all -a'
run this command with default answer, then run this installer again

Reading state information...
tree is already the newest version (1.8.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up grub-pc (2.06-3~deb10u4) ...
/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-0 does not exist, so cannot grub-install to it!
You must correct your GRUB install devices before proceeding:

  DEBIAN_FRONTEND=dialog dpkg --configure grub-pc
  dpkg --configure -a
dpkg: error processing package grub-pc (--configure):
 installed grub-pc package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 grub-pc
BOA [02:09:06] ==> INFO: OpenSSL is 1.1.1n, upgrade to 1.1.1w required
BOA [02:09:06] ==> INFO: PHP SSL Version => OpenSSL/1.1.1w, looks OK
BOA [02:09:06] ==> INFO: Building zlib 1.2.11 from sources first...
BOA [02:09:16] ==> INFO: Building OpenSSL 1.1.1w from sources...
BOA [02:09:16] ==> WAIT: This may take a while, please wait...
BOA [02:13:57] ==> INFO: Installed cURL version 8.0.1, upgrade required
BOA [02:14:32] ==> INFO: Building cURL 8.4.0 from sources...
BOA [02:14:32] ==> WAIT: This may take a while, please wait...
BOA [02:16:20] ==> INFO: Installing Redis server for Devuan/beowulf...
BOA [02:18:12] ==> INFO: Installing VnStat monitor...
BOA [02:18:34] ==> INFO: Upgrading Limited Shell to version 0.9.18.9...
BOA [02:20:42] ==> INFO: Installing ICU libs version 73-1...
BOA [02:20:42] ==> WAIT: This may take a while, please wait...
BOA [02:26:22] ==> INFO: Installing PhpRedis 5.3.7 upgrade for PHP 7.4.33...
BOA [02:26:47] ==> INFO: Installing APCu 5.1.20 upgrade for PHP 7.4.33...
BOA [02:27:03] ==> INFO: Installing igbinary 3.2.12 upgrade for PHP 7.4.33...
BOA [02:27:19] ==> INFO: Installing MCRYPT 1.0.6 upgrade for PHP 7.4.33...
BOA [02:27:32] ==> INFO: Installing UploadProgress 2.0.2 upgrade for PHP 7.4.33...
BOA [02:27:43] ==> INFO: Installing JSMin 3.1.0 upgrade for PHP 7.4.33...
BOA [02:27:55] ==> INFO: Installing Imagick 3.6.0 upgrade for PHP 7.4.33...
BOA [02:28:31] ==> INFO: Installing LibYAML upgrade for PHP...
BOA [02:28:51] ==> INFO: Installing YAML 2.2.3 upgrade for PHP 7.4.33...
/opt/php81/bin/php: Symbol `OnigEncodingEUC_JP' has different size in shared object, consider re-linking
/opt/php81/bin/php: Symbol `OnigEncodingUTF8' has different size in shared object, consider re-linking
BOA [02:29:03] ==> INFO: PHP 8.1.27 rebuild required to fix broken build...
BOA [02:29:03] ==> INFO: Building PHP 8.1.27 from sources...
BOA [02:29:28] ==> INFO: Building PHP 8.1.27 part 1/3
BOA [02:29:28] ==> INFO: Building PHP 8.1.27 part 2/3
BOA [02:30:59] ==> INFO: Building PHP 8.1.27 part 3/3
BOA [02:30:59] ==> WAIT: This may take a while, please wait...
BOA [02:45:41] ==> INFO: Installing PhpRedis 5.3.7 for PHP 8.1.27...
BOA [02:46:06] ==> INFO: Installing APCu 5.1.20 for PHP 8.1.27...
BOA [02:46:22] ==> INFO: Installing igbinary 3.2.12 for PHP 8.1.27...
BOA [02:46:38] ==> INFO: Installing MCRYPT 1.0.6 for PHP 8.1.27...
BOA [02:46:51] ==> INFO: Installing UploadProgress 2.0.2 for PHP 8.1.27...
BOA [02:47:02] ==> INFO: Installing JSMin 3.1.0 for PHP 8.1.27...
BOA [02:47:13] ==> INFO: Installing Imagick 3.6.0 for PHP 8.1.27...
BOA [02:47:32] ==> INFO: Installing YAML 2.2.3 for PHP 8.1.27...

BOA [02:48:13] ==> INFO: Installing Adminer Manager...
BOA [02:48:13] ==> INFO: Adminer Manager installed
BOA [02:48:13] ==> INFO: Building Pure-FTPd server from sources...
BOA [02:49:11] ==> INFO: Installing MySecureShell master-20-03-2015...

BOA [02:49:35] ==> INFO: Installed OpenSSH version 7.9p1, upgrade required
BOA [02:49:35] ==> INFO: Building OpenSSH 9.6p1 from sources...
BOA [02:49:35] ==> WAIT: This may take a while, please wait...
BOA [02:51:25] ==> INFO: Upgrading csf/lfd firewall...
BOA [02:52:28] ==> CARD: Now charging your credit card for this magic show...
BOA [02:52:31] ==> CARD: It will take a moment to process your payment...
BOA [02:52:37] ==> JOKE: Just kidding !!! Enjoy your Aegir Hosting System :)

BOA [02:52:41] ==> Final post-upgrade cleaning, one moment...
BOA [02:52:45] ==> BYE!
```

and an `ALERT: Failed (alrt) Barracuda upgrade on my.server.com at 231225-025246` email:
```
BOA [02:53:14] ==> Skynet Agent v.BOA-5.1.0-head welcomes you aboard!

BOA [02:53:17] ==> MODE: UPGRADE

BOA [02:53:42] ==> VIRT: This system is supported: Linux KVM guest

BOA [02:53:42] ==> Aegir on [my.server.com](http://my.server.com/) Devuan/beowulf x86_64 PHP 7.4

BOA [02:54:22] ==> INFO: Running aptitude full-upgrade...
apt --fix-broken install -y failed.  Error (if any): 0

Displaying the last 15 lines of logfile
  /var/backups/barracuda-upgrade-231225-025301.log
to help troubleshoot this problem

If you see any error with advice to run 'dpkg --configure --force-all -a'
run this command with default answer, then run this installer again

Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up grub-pc (2.06-3~deb10u4) ...
/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-0 does not exist, so cannot grub-install to it!
You must correct your GRUB install devices before proceeding:

  DEBIAN_FRONTEND=dialog dpkg --configure grub-pc
  dpkg --configure -a
dpkg: error processing package grub-pc (--configure):
 installed grub-pc package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 grub-pc
dpkg --configure --force-all -a failed.  Error (if any): 0

Displaying the last 15 lines of logfile
  /var/backups/barracuda-upgrade-231225-025301.log
to help troubleshoot this problem

If you see any error with advice to run 'dpkg --configure --force-all -a'
run this command with default answer, then run this installer again

Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up grub-pc (2.06-3~deb10u4) ...
/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-0 does not exist, so cannot grub-install to it!
You must correct your GRUB install devices before proceeding:

  DEBIAN_FRONTEND=dialog dpkg --configure grub-pc
  dpkg --configure -a
dpkg: error processing package grub-pc (--configure):
 installed grub-pc package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 grub-pc
Setting up grub-pc (2.06-3~deb10u4) ...
BOA [02:55:19] ==> MODE: Devuan Beowulf to Devuan Chimaera upgrade
BOA [02:55:19] ==> RLLY: Have you created a Fresh Backup Snapshot of this VM?
BOA [02:55:25] ==> ATTN: You have to be prepared in case the upgrade will fail
BOA [02:55:25] ==> ATTN: You have to be prepared for a crash of this system
BOA [02:55:25] ==> ATTN: This procedure is well tested but things happen!
BOA [02:55:31] ==> FINE: But you can still hit ctrl-c to stop if you wish
BOA [02:55:31] ==> WAIT: We need a minute to stop all running cron tasks...
BOA [02:55:37] ==> WAIT: This major system upgrade will start in 60s...
BOA [02:55:53] ==> WAIT: ...it will start in 45s...
BOA [02:56:09] ==> WAIT: ...it will start in 30s...
BOA [02:56:25] ==> WAIT: ...it will start in 15s...
BOA [02:56:31] ==> ATTN: Ten seconds left to hit ctrl-c to stop...
BOA [02:56:42] ==> INFO: Devuan Beowulf to Devuan Chimaera upgrade in progress...
BOA [02:56:42] ==> HINT: Command to run in another terminal window to watch details
BOA [02:56:42] ==> CMND: tail -f /var/backups/barracuda-upgrade-231225-025301.log
BOA [02:57:31] ==> ALRT! I can not continue until dpkg --audit is clean
BOA [02:57:31] ==> ALRT! The following packages are only half configured, probably due to problems
configuring them the first time.  The configuration should be retried using
dpkg --configure <package> or the configure menu option in dselect:
 grub-pc              GRand Unified Bootloader, version 2 (PC/BIOS version)
BOA [02:57:31] ==> ALRT! Aborting installer NOW!
```

I ran `DEBIAN_FRONTEND=dialog dpkg --configure grub-pc` as the emails suggest but I am still stuck there.

Any suggestions?

**Comment by omega8cc** [comment]
This line means that there are some packages locked and effectively blocking the upgrade. It doesn’t happen on default BOA instances regularly upgraded, though. You should run this command, unlock the packages and run the major upgrade procedure again.

`BOA [02:57:31] ==> ALRT! I can not continue until dpkg —audit is clean`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fotiDim** [comment]
@omega8cc that worked, thanks! For the record, this is what I did after I got the error emails:

```
server:~# dpkg --audit
The following packages are only half configured, probably due to problems
configuring them the first time.  The configuration should be retried using
dpkg --configure <package> or the configure menu option in dselect:
 grub-pc              GRand Unified Bootloader, version 2 (PC/BIOS version)

server:~# DEBIAN_FRONTEND=dialog dpkg --configure grub-pc
Setting up grub-pc (2.06-3~deb10u4) ...
Installing for i386-pc platform.
Installation finished. No error reported.
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.19.0-25-amd64
Found initrd image: /boot/initrd.img-4.19.0-25-amd64
Found linux image: /boot/vmlinuz-4.9.0-19-amd64
Found initrd image: /boot/initrd.img-4.9.0-19-amd64
Warning: os-prober will be executed to detect other bootable partitions.
Its output will be used to detect bootable binaries on them and create new boot entries.
done
server:~# dpkg --configure -a
server:~# dpkg --audit
server:~# service clean-boa-env start
Starting clean-boa-env: clean-boa-env 1 nothing to do.
clean-boa-env 2 nothing to do.
clean-boa-env 3 nothing to do.
clean-boa-env 4 nothing to do.
clean-boa-env 5 nothing to do.
```
